nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.2.cjs

npmRegistryServer: 'https://registry.npmjs.org/'

enableGlobalCache: true
enableScripts: true
enableStrictSsl: true
enableNetwork: true

supportedArchitectures:
  os: ['current']
  cpu: ['current']

preferInteractive: false
enableImmutableInstalls: false
enableMirror: false
defaultSemverRangePrefix: ''

httpTimeout: 60000
httpRetry: 3
networkConcurrency: 50

compressionLevel: mixed
cacheFolder: '.yarn/cache'

enableInlineBuilds: false
checksumBehavior: update

logFilters:
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard
  - code: YN0028
    level: discard

progressBarStyle: default
