export const testIdsConstant = {
  alertDialog: {
    content: 'alert-dialog-content',
    description: 'alert-dialog-description',
    footer: 'alert-dialog-footer',
    overlay: 'alert-dialog-overlay',
    portal: 'alert-dialog-portal',
    title: 'alert-dialog-title',
  },
  avatar: {
    image: 'avatar-image',
    root: 'avatar-root',
  },
  badge: 'badge',
  blurView: 'blur-view',
  bottomSheet: {
    content: 'bottom-sheet-content',
    modal: 'bottom-sheet-modal',
    modalContent: 'bottom-sheet-modal-content',
    root: 'bottom-sheet-root',
  },
  button: 'base-button',
  carousel: {
    action: 'carousel-action',
    default: 'carousel-default',
    defaultSkeleton: 'carousel-default-skeleton',
    dot: 'carousel-dot',
    dots: 'carousel-dots',
    dotsContainer: 'carousel-dots-container',
    image: 'carousel-image',
    item: 'carousel-item',
    itemButton: 'carousel-item-button',
    itemImage: 'carousel-item-image',
    itemTitle: 'carousel-item-title',
    parallax: 'carousel-parallax',
    parallaxSkeleton: 'carousel-parallax-skeleton',
    root: 'carousel-root',
    video: 'carousel-video',
    youtube: 'carousel-youtube',
  },
  confirmationCodeField: {
    cell: 'confirmation-code-field-cell',
    root: 'confirmation-code-field-root',
  },
  dateTimePicker: {
    backToMonthGridButton: 'date-time-picker-back-to-month-grid-button',
    cancelButton: 'date-time-picker-cancel-button',
    confirmButton: 'date-time-picker-confirm-button',
  },
  fastImage: 'fastImage',
  form: {
    checkBoxField: 'form-checkbox-field',
    choiceListOption: 'form-choice-list-option',
    confirmationCodeField: 'form-confirmation-code-field',
    datePickerFieldModal: 'form-date-picker-field-modal',
    datePickerFieldTrigger: 'form-date-picker-field-trigger',
    inputField: 'form-input-field',
    radioGroupField: 'form-radio-group-field',
    switchField: 'form-switch-field',
    textAreaField: 'form-text-area-field',
  },
  videoPlayer: 'video-player',
  youtubePlayer: 'youtube-player',
} as const;
